### ISSUE TITLE
Fetch page ratings

### ISSUE THREAD

**Issue by rostockahoi** [boscho87/facebook-connector#31]
Hi, would be nice to fetch Facebook page ratings. Is that possible?

**Comment by boscho87** [comment]
Hey is there no other plugin you could use... or do you use this plugin and you want this feature added?=

**Comment by boscho87** [comment]
hey i will create a new plugin, because the codebase of this is kind of a mess. but maybe you can user this instead:

okay i now its a long time ago since you created this issue.

https://plugins.craftcms.com/facebook
