### ISSUE TITLE
Tag a 1.2.7 release?

### ISSUE THREAD

**Issue by angrybrad** [boscho87/facebook-connector#32]
Any chance you could tag a 1.2.7 release now that https://github.com/boscho87/facebook-connector/commit/4b64378e267893fee57f9dc11daf7992d8df5469 has been merged in?

Without that, installing this plugin from the Plugin Store will fail for anyone not running a minimum stability of dev in their composer.json file.

**Comment by Nielskrikken** [comment]
I would like this to happen as well. Can this be done?

**Comment by boscho87** [comment]
@angrybrad , @Nielskrikken 
I tagged a new Release... but i think the blugin is way to buggy :(
