### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by Nielskrikken** [boscho87/facebook-connector#33]
I'm getting the following error while trying to run the command 'php craft facebook-connector/entry-fetch/fetch-list' :

Exception 'Facebook\Exceptions\FacebookSDKException' with message 'You must provide an access token.'

I've created an Facebook API, i Filled all the fiels in craft 

Am I missing something?

**Comment by FrancisBou** [comment]
Even when the client ID / secret is loaded in the plugin settings, this error still pops up, therefore it's impossible to load facebook posts.

**Comment by henrypenny** [comment]
There isn't a token field in the plugin settings. I've added an api key and secret. But I get the OP's error.

**Comment by boscho87** [comment]
not in the settings, in the widget on the dashboard.

- FYI this plugin will no longer be Updated. A Better one is in development here: 
https://github.com/boscho87/facebook-fetch

i will anounce this here and will mark this one as depricated as soon the new is in the pluings section of the craft cms
