### ISSUE TITLE
Error on saving existing entries

### ISSUE THREAD

**Issue by mlmarloth** [boscho87/facebook-connector#34]
## Description
When saving existing entries or creating new sections etc, the FacebookConnector throws an error. 

## Expected behavior
Changes should just save, not sure how the plugin comes into play here

## Actual behavior
include(/home/someuser/vendor/../fieldconfig.php): failed to open stream: No such file or directory

## Steps to reproduce the error
1. Save any entry

## Context
in /home/someuser/vendor/itscoding/facebook-connector/src/services/ConfigFileLoader.php
 }
    }
 
    /**
     * @return string
     */
    public function getConfigFile(): callable
    {
        if ($this->configFile) {
            $config = include $this->configFile;
            if (is_callable($config)) {
                return $config;
            }
        }
        return function () {
            return [];
        };
    }

## Environment
* Version: 1.4.0
* Craft CMS: 3.3.0.1
* Quering Facebook on API v4.0

**Comment by mlmarloth** [comment]
The plugin otherwise works in fetching posts.

**Comment by mlmarloth** [comment]
`public function init()
    {
	$path = \Craft::$app->vendorPath . '/../fieldconfig.php';
        if (file_exists($path)){
            $this->configFile = $path;
        } else {
            $this->configFile = NULL;
        }
    }

    /**
     * @return string
     */
    public function getConfigFile(): callable
    {
        if (!empty($this->configFile)) {
            $config = include $this->configFile;
            if (is_callable($config)) {
                return $config;
            }
        }
        return function () {
            return [];
        };
    }`
Not sure if I understand this correctly, but made slight changes

**Comment by boscho87** [comment]
hey, sorry im too l8...
the codebase of this plugin is kind of a mess. 

i will create a new Plugin (only to fetch data from facebook, not too post on facebook)
this pluign is deprecated.
